import React, { useState } from 'react';
import { Eye, EyeOff } from 'lucide-react';
import { FormDialog } from '../../../components/shared/FormDialog';
import { Input } from '../../../components/shared/Input';
import { Select } from '../../../components/shared/Select';

export interface UserFormValues {
  name: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  email: string;
  password: string;
  roleId: string;
  authProvider: string;
}

export interface UserFormDialogProps {
  isOpen: boolean;
  /** True = edit an existing user; false = create. */
  isEditing: boolean;
  values: UserFormValues;
  onChange: (field: keyof UserFormValues, value: string) => void;
  roles: Array<{ id: string | number; name: string }>;
  /** Whether the Cognito auth provider is available (adds the provider picker on create). */
  cognitoEnabled: boolean;
  error?: string | null;
  submitting?: boolean;
  onSubmit: () => void;
  onClose: () => void;
}

/**
 * Add / edit user dialog. Replaces the legacy inline panel with the shared
 * FormDialog + Input/Select so it matches the rest of Access Control (tokens,
 * dark mode, focus handling, Enter-to-submit). Business logic stays in
 * UserManagement — this component owns only presentation.
 */
export const UserFormDialog: React.FC<UserFormDialogProps> = ({
  isOpen,
  isEditing,
  values,
  onChange,
  roles,
  cognitoEnabled,
  error,
  submitting = false,
  onSubmit,
  onClose,
}) => {
  const [showPassword, setShowPassword] = useState(false);
  const isLocal = values.authProvider === 'LOCAL';

  const roleOptions = roles.map((r) => ({ value: String(r.id), label: r.name }));
  const providerOptions = [
    { value: 'COGNITO', label: 'AWS Cognito' },
    { value: 'LOCAL', label: 'Local account' },
  ];

  return (
    <FormDialog
      isOpen={isOpen}
      onClose={onClose}
      title={isEditing ? 'Edit user' : 'Add user'}
      description={
        isEditing
          ? 'Update this user’s profile and role.'
          : 'Invite a new user and assign their role.'
      }
      onSubmit={onSubmit}
      submitText={isEditing ? 'Save changes' : 'Create user'}
      isSubmitting={submitting}
      error={error ?? null}
      size="lg"
    >
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <Input
          label="First name"
          value={values.firstName}
          onChange={(e) => onChange('firstName', e.target.value)}
          placeholder="First name"
          fullWidth
          autoFocus
        />
        <Input
          label="Last name"
          value={values.lastName}
          onChange={(e) => onChange('lastName', e.target.value)}
          placeholder="Last name"
          fullWidth
        />
        <Input
          label="Phone number"
          value={values.phoneNumber}
          onChange={(e) => onChange('phoneNumber', e.target.value)}
          placeholder="Phone number"
          fullWidth
        />
        <Input
          label="Email"
          type="email"
          value={values.email}
          onChange={(e) => onChange('email', e.target.value)}
          placeholder="name@company.com"
          disabled={isEditing}
          helperText={isEditing ? 'Email can’t be changed after creation.' : undefined}
          fullWidth
        />

        {isLocal ? (
          <Input
            label={isEditing ? 'Password (leave blank to keep current)' : 'Password'}
            type={showPassword ? 'text' : 'password'}
            value={values.password}
            onChange={(e) => onChange('password', e.target.value)}
            placeholder={isEditing ? 'New password (optional)' : 'Password'}
            fullWidth
            rightIcon={
              <button
                type="button"
                onClick={() => setShowPassword((s) => !s)}
                aria-label={showPassword ? 'Hide password' : 'Show password'}
                className="text-content-tertiary hover:text-content-primary focus:outline-none"
              >
                {showPassword ? <EyeOff size={18} aria-hidden="true" /> : <Eye size={18} aria-hidden="true" />}
              </button>
            }
          />
        ) : (
          <Input
            label="Password"
            value="Auto-generated by Cognito"
            disabled
            helperText="A temporary password is emailed to the user."
            fullWidth
          />
        )}

        <Select
          label="Role"
          value={values.roleId}
          onChange={(value) => onChange('roleId', value)}
          options={roleOptions}
          placeholder="Select a role"
          fullWidth
        />

        {!isEditing && cognitoEnabled && (
          <div className="sm:col-span-2">
            <Select
              label="Authentication provider"
              value={values.authProvider}
              onChange={(value) => onChange('authProvider', value)}
              options={providerOptions}
              fullWidth
            />
          </div>
        )}
      </div>
    </FormDialog>
  );
};

export default UserFormDialog;
